### ISSUE TITLE
64-Bit JIT/Backwards compatibility regression

### ISSUE THREAD

**Issue by sae42** [Microsoft/dotnet-framework-early-access#15]
MSIL that ran correctly with earlier .NET framework fails due to 64-bit JIT optimizations in 4.7.2 preview build
# Version Info
.NET 4.7.2 Preview Build 3052, Windows 10 1703 (OS Build 15063:909)

# Description
This looks like a regression in the 64-bit jitter. The attached x.il can be used to repro by running ilasm x.il and running x.exe. The correct output should be 'Pass', but will show 'Fail'. If you use the /32BitPreferred arg to ilasm (or corflags) the output will correctly show 'Pass'. Running in 64-bit mode on earlier .NET framework versions (including 4.7) will show 'Pass'. Disabling RyuJit by either COMPLUS_UseLegacyJit=1 or COMPLUS_JitMinOpts=1 will also result in 'Pass'.
 

[x.txt](https://github.com/Microsoft/dotnet-framework-early-access/files/1794424/x.txt)

**Comment by briansull** [comment]
This is now fixed in .NET CoreCLR
https://github.com/dotnet/coreclr/pull/16860

**Comment by briansull** [comment]
Does this bug that you reported have a significant impact on any currently deployed programs?
Or is it just something that you noticed and reported?

**Comment by sae42** [comment]
Hi Brian, it will have a serious impact if the fix doesn't make RTW 4.7.2 since it may break existing apps. Our compiler does not target Core CLR so we're only interested in the desktop .NET framework. Can you confirm the fix will make RTW 4.7.2 (or better still an updated preview)?

**Comment by briansull** [comment]
Can you tell me what "our compiler" is?

I can provide you additional information about the timeline after we can assess the imapct of this better.

**Comment by briansull** [comment]
Is  the impacted product the MicroFocus COBOL compiler?

**Comment by sae42** [comment]
That's correct.

**Comment by briansull** [comment]
@sae42 Can you email me using your direct email address?
to briansul@microsoft.com

**Comment by AlexGhiondea** [comment]
@sae42 I would like to understand more about the impact this issue is having. 
 
Could you reach out to me at dotnetprerelfeedback_at_microsoft_dot_com with more information?

**Comment by briansull** [comment]
Can also be closed
