### ISSUE TITLE
Backwards compatibility issue with INITBLK and CPBLK instructions (64-Bit)

### ISSUE THREAD

**Issue by sae42** [Microsoft/dotnet-framework-early-access#22]
# Use of INITBLK and CPBLK MSIL instructions can cause compatibility issues when running under .NET 4.7.2 preview

# Version Info
.NET 4.7.2 Preview Build 3052, Windows 10 1703 (OS Build 15063:909)

# Description
The attached IL fragment can be used for a repro. Issue occurs only in 64-bit and when the IL is compiled using ilasm and the /debug (or /debug=impl) flags.  Note, compiling with /debug=opt does not trigger a problem. The issue seems related to the use of the MSIL INITBLK and CPBLK instructions and specifically when data length is 2, 4 or 8 bytes. The attached example only uses CPBLK - I can supply other examples if necessary.

[x1mod.txt](https://github.com/Microsoft/dotnet-framework-early-access/files/1830062/x1mod.txt)

**Comment by briansull** [comment]
This issue was reported and has been fixed.

**Comment by briansull** [comment]
GitHub changset with fix
https://github.com/dotnet/coreclr/pull/16700

**Comment by sae42** [comment]
Excellent news. Thanks!
