### ISSUE TITLE
.NET Frame 4.8 cannot beinstalled

### ISSUE THREAD

**Issue by msedi** [Microsoft/dotnet-framework-early-access#27]
# Issue Title

Setup cannot continue as the package does not apply to this operating system. Please refer to <A HREF="http://go.microsoft.com/fwlink/?LinkId=874340">this page</A> for more information about the supported operating systems. 

# Version info 

.NET Framework 4.8 Early Build
Windows 7 6.1 (Build 7601, Service Pack 1)

# General

I have attach the log file from collect.exe

[vslogs.zip](https://github.com/Microsoft/dotnet-framework-early-access/files/2079510/vslogs.zip)

**Comment by hypeartist** [comment]
> Windows 7 is not supported
Why? And will it be supported at next previews/final of 4.8?

**Comment by msedi** [comment]
I just saw in the blog post. Sorry for that. Although it's a little bit sad that the directions are so Win10 like.
