### ISSUE TITLE
Unable to install on Windows 10

### ISSUE THREAD

**Issue by coryflucas** [Microsoft/dotnet-framework-early-access#4]
# Version info 

.NET Framework 4.7.1 build 2539
Windows 10 v1703 (OS Build 15063.608)

# General

When I run the installer I receive a Setup Failed message which states the Preview Developer pack is not support on my operating system.  Build 2538 installed without issue.

Relevant line from the installer log:
```
Setting string variable 'OSBuildNumber' to value '15063'
```
and
```
Error 0x81f40001: Bundle condition evaluated to false: ((VersionNT = v6.1 AND ServicePackLevel >= 1) OR       (VersionNT = v6.2 AND NOT (OSInstallationType = "Client")) OR       (VersionNT = v6.3) OR       (VersionNT = v10.0 AND (OSBuildNumber > 15063 OR OSBuildNumber = 14393 ) ) OR       (VersionNT > v10.0))
```

**Comment by imkow** [comment]
I got this problem 2

**Comment by osoykan** [comment]
Same here

**Comment by paule96** [comment]
same here

**Comment by vivmishra** [comment]
This is expected/known issue for now. 
The RTM version of the product will be carrying the support for Windows 10 v1703 (OS Build 15063).

**Comment by coryflucas** [comment]
What OS versions are supported? The README.md says that Windows 10 Anniversary Update is supported.

**Comment by vivmishra** [comment]
The readme.md has the correct list of OS versions that are supported with the current build. 

Yes, Windows 10 Anniversary Update is supported. 
This issue was about Windows 10 **Creators** Update, that will be supported at RTM.

**Comment by coryflucas** [comment]
I understand now, I guess I assumed a newer version would be supported.

**Comment by rastographics** [comment]
@vivmishra please can you give estimate for support of 1703? it is frustrating I cannot use this because I'm on latest update of windows. thanks

**Comment by otoolepw** [comment]
Hi @vivmishra, is there an update on @rastographics issue? I'm experiencing the same problem. Thanks

**Comment by plang321** [comment]
@vivmishra or anyone else who might know -

I'm on Windows 10 Version 1511 (OS build 10586) and cannot install the .NET Framework 4.7 and above.  I get the Operating System not supported error no matter which version I choose (the stand alone or developer pack).  Any idea if this will ever be addressed?

**Comment by vivmishra** [comment]
Windows 10 Version 1511 (OS build 10586) has been out of support for sometime now. You need to upgrade your Win 10 OS.

**Comment by plang321** [comment]
@vivmishra - do I need to completely reinstall a new version of Windows 10 or can I do an in-place upgrade?

**Comment by plang321** [comment]
@vivmishra - The version I called out above was downloaded through the subscriber downloads (I'm a member through the organization I work for).

Do I need to reinstall Windows 10, or is there a way to just update to the latest version without having to reinstall everything?
