### ISSUE TITLE
Merge ObjectIdGenerator Changes To 4.8

### ISSUE THREAD

**Issue by Alois-xx** [Microsoft/dotnet-framework-early-access#46]
# Merge ObjectIdGenerator fix from .NET Core to Desktop
We are hitting the issue 
https://github.com/dotnet/corefx/issues/24902
with regular .NET Framework now. It would be good to merge the fixes done there back
to the full .NET Framework or as quick fix at least increase the fixed hash values to support at
least 30 million objects in the serialized data.

**Comment by vivmishra** [comment]
@danmosemsft ; @tarekgh

**Comment by danmosemsft** [comment]
@Alois-xx only https://github.com/dotnet/corefx/pull/17949 is needed right?

**Comment by Alois-xx** [comment]
Yes exactly.


Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: Dan Moseley <notifications@github.com> Datum: 12.12.18  19:24  (GMT+01:00) An: Microsoft/dotnet-framework-early-access <dotnet-framework-early-access@noreply.github.com> Cc: Alois-xx <akraus1@gmx.de>, Mention <mention@noreply.github.com> Betreff: Re: [Microsoft/dotnet-framework-early-access] Merge ObjectIdGenerator
  Changes To 4.8 (#46) 
@Alois-xx only dotnet/corefx#17949 is needed right?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Microsoft/dotnet-framework-early-access","title":"Microsoft/dotnet-framework-early-access","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Microsoft/dotnet-framework-early-access"}},"updates":{"snippets":[{"icon":"PERSON","message":"@danmosemsft in #46: @Alois-xx only https://github.com/dotnet/corefx/pull/17949 is needed right?"}],"action":{"name":"View Issue","url":"https://github.com/Microsoft/dotnet-framework-early-access/issues/46#issuecomment-446691401"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Microsoft/dotnet-framework-early-access/issues/46#issuecomment-446691401",
"url": "https://github.com/Microsoft/dotnet-framework-early-access/issues/46#issuecomment-446691401",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Alois-xx** [comment]
The project is rather large and we had already some consultants from MS for some days to check porting parts of the application to .NET Core. Since a major part relies on IAsyncResult which will never be ported to .NET Core and other parts rely on Workflow Foundation where also no port is planned there is little hope to switch over to .NET Core. 

In our case the used datasets increase in size where we now hit the object graph limit with sometimes. 12 million objects is not much. I would be ok if you add some more prime numbers to lets say 50 million objects to be safe for quite some time and we get around to redesign things to not use BinaryFormatter.
We do not need the full prime number generator from Dictionary. Some strategic primes in 5 million steps would do it.

**Comment by Alois-xx** [comment]
The project is rather large and we had already some consultants from MS for some days to check porting parts of the application to .NET Core. Since a major part relies on IAsyncResult which will never be ported to .NET Core and other parts rely on Workflow Foundation where also no port is planned there is little hope to switch over to .NET Core. 

In our case the used datasets increase in size where we now hit the object graph limit with sometimes. 12 million objects is not much. I would be ok if you add some more prime numbers to lets say 50 million objects to be safe for quite some time and we get around to redesign things to not use BinaryFormatter.
We do not need the full prime number generator from Dictionary. Some strategic primes in 5 million steps would do it. 

The change dotnet/corefx#17949 is already part of .NET 4.7.2 which is hidden behind an AppCompat switch (see https://aloiskraus.wordpress.com/2018/05/06/serialization-performance-update-with-net-4-7-2/). This is more about https://github.com/dotnet/corefx/pull/25509 to share the prime number generation from dictionary inside Binaryformatter.

**Comment by jast313** [comment]
My project is in the same situation as Alois. For a variety of reasons, we can not switch to .NET core (even though I would love to), and I am reaching this limitation.

An increase from 12m to 50m like Alois requested would be perfect for my application... danmosemsft, your consideration is greatly appreciated.

On a related note, the "Switch.System.Runtime.Serialization.UseNewMaxArraySize=true" is very useful... without this, I would not be able to continue using BinaryFormatter. Thanks for implementing this in .NET4.7.2

-Jas
directmotion.com

**Comment by danmosemsft** [comment]
@viktorhofer has made the following change in the 4.8 branch.

```
37a38,41
>         private static readonly int[] sizesWithMaxArraySwitch = {
>             5, 11, 29, 47, 97, 197, 397, 797, 1597, 3203, 6421, 12853, 25717, 51437,
>             102877, 205759, 411527, 823117, 1646237, 3292489, 6584983, 13169977, 26339969,
>             52679969, 105359939, 210719881, 421439783 };
152a157,159
>             
>             // Use the array with more pre-computed prime numbers if the max array switch is on.
>             int[] arr = AppContextSwitches.UseNewMaxArraySize ? sizesWithMaxArraySwitch : sizes;
154,155c161,162
<             for (i=0, currSize=m_currentSize; i<sizes.Length && sizes[i]<=currSize; i++);
<             if (i==sizes.Length) {
---
>             for (i=0, currSize=m_currentSize; i<arr.Length && arr[i]<=currSize; i++);
>             if (i==arr.Length) {
160c167
<             m_currentSize = sizes[i];
---
>             m_currentSize = arr[i];

```

If all goes well this should go out in 4.8.

**Comment by Alois-xx** [comment]
@danmosemsft: Thanks! Much appreciated!

**Comment by danmosemsft** [comment]
Thank you both for flagging this. I'll close this now then.
