### ISSUE TITLE
Any chance of porting ContidionalWeakTable IEnumerable support?

### ISSUE THREAD

**Issue by kekekeks** [Microsoft/dotnet-framework-early-access#56]
It was added to coreclr in Jan 2017 and now lives in corefx repo. 

Unfortunately that's one of the classes that people can't just copy-paste to their programs to get the new features, because it relies on DependentHandle which is private to a particular runtime.

**Comment by danmosemsft** [comment]
@kekekeks could you please describe your scenarios?

**Comment by kekekeks** [comment]
Currently we have some kind of WeakEventManager implementation that needs to enumerate all event sources to compact event handler list for dead subscribers.

The reference graph looks somewhat like this:

static variable -> `ConditionalWeakTable` of event sources -> SubscriptionList -> `List<WeakReference>` of event subscribers.

When subscriber is collected there is no way to dispose the subscription list until event is triggered or event handler is added/removed unless ConditionalWeakTable supports IEnumerable. In case of .NET Core and Mono it does. We want to be able to use the code with the legacy .NET Framework.

**Comment by danmosemsft** [comment]
Could you construct such a table using WeakReference alone?  

cc @stephentoub 

https://github.com/dotnet/corefx/issues/14387

**Comment by kekekeks** [comment]
`ConditionalWeakTable` is more GC efficient since it uses DependentHandle: GC is aware that it can mark the the associated value as unused alongside with the key. Implementing a custom table with WeakReference as keys would cause more object to survive through the collection and be promoted to the next GC generation which is not a desirable behavior.

**Comment by danmosemsft** [comment]
@kekekeks thanks for the suggestion. We have discussed this and do not plan to do the port. We do not believe the value and need is high enough to justify the cost and risk.
